export const COMPANY_VERIFY_REQUEST = 'COMPANY_VERIFY_REQUEST';
export const COMPANY_VERIFY_SUCCESS = 'COMPANY_VERIFY_SUCCESS';
export const COMPANY_VERIFY_FAILURE = 'COMPANY_VERIFY_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT        = 'LOGOUT';
export const CLEAR_COMPANY = 'CLEAR_COMPANY';
