export const COMPANIES_FETCH_REQUEST = 'COMPANIES_FETCH_REQUEST';
export const COMPANIES_FETCH_SUCCESS = 'COMPANIES_FETCH_SUCCESS';
export const COMPANIES_FETCH_FAILURE = 'COMPANIES_FETCH_FAILURE';

export const COMPANY_UPDATE_REQUEST = 'COMPANY_UPDATE_REQUEST';
export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS';
export const COMPANY_UPDATE_FAILURE = 'COMPANY_UPDATE_FAILURE';
export const COMPANY_UPDATE_RESET   = 'COMPANY_UPDATE_RESET';
